### ISSUE TITLE
Encoding of text files

### ISSUE THREAD

**Issue by njellinas** [HLTSingapore/Emotional-Speech-Data#1]
The encodings are messed up, some chinese files have been saved with gb2312, some with utf-16-le and I found even an english file saved with the chinese encoding

**Comment by Edresson** [comment]
Same here,  in addition, some files do not use "\t" as the separator, but it uses " " (space).

**Comment by unilight** [comment]
I used `file -i` to try to infer what encoding was used for each file:

0001/0001.txt: text/plain; charset=iso-8859-1
0002/0002.txt: text/plain; charset=iso-8859-1
0003/0003.txt: text/plain; charset=utf-16le
0004/0004.txt: text/plain; charset=iso-8859-1
0005/0005.txt: text/plain; charset=iso-8859-1
0006/0006.txt: text/plain; charset=utf-16le
0007/0007.txt: text/plain; charset=utf-16le
0008/0008.txt: text/plain; charset=utf-16le
0009/0009.txt: text/plain; charset=iso-8859-1
0010/0010.txt: text/plain; charset=utf-16le
0011/0011.txt: text/plain; charset=us-ascii
0012/0012.txt: text/plain; charset=utf-16le
0013/0013.txt: text/plain; charset=utf-16le
0014/0014.txt: text/plain; charset=utf-16le
0015/0015.txt: text/plain; charset=us-ascii
0016/0016.txt: text/plain; charset=iso-8859-1
0017/0017.txt: text/plain; charset=iso-8859-1
0018/0018.txt: text/plain; charset=utf-16le
0019/0019.txt: text/plain; charset=utf-16le
0020/0020.txt: text/plain; charset=us-ascii

so messed up lol

**Comment by agkphysics** [comment]
I created a processing script [here](https://github.com/Strong-AI-Lab/emotion/blob/master/datasets/ESD/process.py) which extracts transcripts and other annotations.

Along with the encoding differences, there seem to be some transcripts which are incorrect or incomplete, which I have tried to correct.
